name: pose_detection
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Camera access
  camera: ^0.11.0+1
  # ML Kit Pose Detection (Underlying tech is MediaPipe)
  google_mlkit_pose_detection: ^0.12.0
  # For handling permissions if needed (optional but recommended)
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
